<?php
/**
 * Cluster
 *
 * PHP version 5
 *
 * @category Class
 * @package  Aylien\NewsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aylien\NewsApi\Models;

use \ArrayAccess;
use \Aylien\NewsApi\ObjectSerializer;

/**
 * Cluster Class Doc Comment
 *
 * @category Class
 * @package  Aylien\NewsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Cluster implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Cluster';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'earliest_story' => '\DateTime',
        'id' => 'int',
        'latest_story' => '\DateTime',
        'location' => '\Aylien\NewsApi\Models\Location',
        'representative_story' => '\Aylien\NewsApi\Models\RepresentativeStory',
        'story_count' => 'int',
        'time' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'earliest_story' => 'date-time',
        'id' => 'int64',
        'latest_story' => 'date-time',
        'location' => null,
        'representative_story' => null,
        'story_count' => 'int32',
        'time' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'earliest_story' => 'earliest_story',
        'id' => 'id',
        'latest_story' => 'latest_story',
        'location' => 'location',
        'representative_story' => 'representative_story',
        'story_count' => 'story_count',
        'time' => 'time'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'earliest_story' => 'setEarliestStory',
        'id' => 'setId',
        'latest_story' => 'setLatestStory',
        'location' => 'setLocation',
        'representative_story' => 'setRepresentativeStory',
        'story_count' => 'setStoryCount',
        'time' => 'setTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'earliest_story' => 'getEarliestStory',
        'id' => 'getId',
        'latest_story' => 'getLatestStory',
        'location' => 'getLocation',
        'representative_story' => 'getRepresentativeStory',
        'story_count' => 'getStoryCount',
        'time' => 'getTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['earliest_story'] = isset($data['earliest_story']) ? $data['earliest_story'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['latest_story'] = isset($data['latest_story']) ? $data['latest_story'] : null;
        $this->container['location'] = isset($data['location']) ? $data['location'] : null;
        $this->container['representative_story'] = isset($data['representative_story']) ? $data['representative_story'] : null;
        $this->container['story_count'] = isset($data['story_count']) ? $data['story_count'] : null;
        $this->container['time'] = isset($data['time']) ? $data['time'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets earliest_story
     *
     * @return \DateTime|null
     */
    public function getEarliestStory()
    {
        return $this->container['earliest_story'];
    }

    /**
     * Sets earliest_story
     *
     * @param \DateTime|null $earliest_story Publication date of the earliest story in cluster
     *
     * @return $this
     */
    public function setEarliestStory($earliest_story)
    {
        $this->container['earliest_story'] = $earliest_story;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id ID of the cluster which is a unique identification
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets latest_story
     *
     * @return \DateTime|null
     */
    public function getLatestStory()
    {
        return $this->container['latest_story'];
    }

    /**
     * Sets latest_story
     *
     * @param \DateTime|null $latest_story Publication date of the latest story in cluster
     *
     * @return $this
     */
    public function setLatestStory($latest_story)
    {
        $this->container['latest_story'] = $latest_story;

        return $this;
    }

    /**
     * Gets location
     *
     * @return \Aylien\NewsApi\Models\Location|null
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param \Aylien\NewsApi\Models\Location|null $location location
     *
     * @return $this
     */
    public function setLocation($location)
    {
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets representative_story
     *
     * @return \Aylien\NewsApi\Models\RepresentativeStory|null
     */
    public function getRepresentativeStory()
    {
        return $this->container['representative_story'];
    }

    /**
     * Sets representative_story
     *
     * @param \Aylien\NewsApi\Models\RepresentativeStory|null $representative_story representative_story
     *
     * @return $this
     */
    public function setRepresentativeStory($representative_story)
    {
        $this->container['representative_story'] = $representative_story;

        return $this;
    }

    /**
     * Gets story_count
     *
     * @return int|null
     */
    public function getStoryCount()
    {
        return $this->container['story_count'];
    }

    /**
     * Sets story_count
     *
     * @param int|null $story_count Number of stories associated with the cluster
     *
     * @return $this
     */
    public function setStoryCount($story_count)
    {
        $this->container['story_count'] = $story_count;

        return $this;
    }

    /**
     * Gets time
     *
     * @return \DateTime|null
     */
    public function getTime()
    {
        return $this->container['time'];
    }

    /**
     * Sets time
     *
     * @param \DateTime|null $time Time of the event
     *
     * @return $this
     */
    public function setTime($time)
    {
        $this->container['time'] = $time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


