<?php
/**
 * Histograms
 *
 * PHP version 5
 *
 * @category Class
 * @package  Aylien\NewsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aylien\NewsApi\Models;

use \ArrayAccess;
use \Aylien\NewsApi\ObjectSerializer;

/**
 * Histograms Class Doc Comment
 *
 * @category Class
 * @package  Aylien\NewsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Histograms implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Histograms';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'field' => 'string',
        'intervalEnd' => 'int',
        'intervalStart' => 'int',
        'intervalWidth' => 'int',
        'intervals' => '\Aylien\NewsApi\Models\HistogramInterval[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'field' => null,
        'intervalEnd' => 'int32',
        'intervalStart' => 'int32',
        'intervalWidth' => 'int32',
        'intervals' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'field' => 'field',
        'intervalEnd' => 'interval.end',
        'intervalStart' => 'interval.start',
        'intervalWidth' => 'interval.width',
        'intervals' => 'intervals'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'field' => 'setField',
        'intervalEnd' => 'setIntervalEnd',
        'intervalStart' => 'setIntervalStart',
        'intervalWidth' => 'setIntervalWidth',
        'intervals' => 'setIntervals'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'field' => 'getField',
        'intervalEnd' => 'getIntervalEnd',
        'intervalStart' => 'getIntervalStart',
        'intervalWidth' => 'getIntervalWidth',
        'intervals' => 'getIntervals'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['field'] = isset($data['field']) ? $data['field'] : null;
        $this->container['intervalEnd'] = isset($data['intervalEnd']) ? $data['intervalEnd'] : null;
        $this->container['intervalStart'] = isset($data['intervalStart']) ? $data['intervalStart'] : null;
        $this->container['intervalWidth'] = isset($data['intervalWidth']) ? $data['intervalWidth'] : null;
        $this->container['intervals'] = isset($data['intervals']) ? $data['intervals'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets field
     *
     * @return string|null
     */
    public function getField()
    {
        return $this->container['field'];
    }

    /**
     * Sets field
     *
     * @param string|null $field field
     *
     * @return $this
     */
    public function setField($field)
    {
        $this->container['field'] = $field;

        return $this;
    }

    /**
     * Gets intervalEnd
     *
     * @return int|null
     */
    public function getIntervalEnd()
    {
        return $this->container['intervalEnd'];
    }

    /**
     * Sets intervalEnd
     *
     * @param int|null $intervalEnd The end interval of the histogram
     *
     * @return $this
     */
    public function setIntervalEnd($intervalEnd)
    {
        $this->container['intervalEnd'] = $intervalEnd;

        return $this;
    }

    /**
     * Gets intervalStart
     *
     * @return int|null
     */
    public function getIntervalStart()
    {
        return $this->container['intervalStart'];
    }

    /**
     * Sets intervalStart
     *
     * @param int|null $intervalStart The start interval of the histogram
     *
     * @return $this
     */
    public function setIntervalStart($intervalStart)
    {
        $this->container['intervalStart'] = $intervalStart;

        return $this;
    }

    /**
     * Gets intervalWidth
     *
     * @return int|null
     */
    public function getIntervalWidth()
    {
        return $this->container['intervalWidth'];
    }

    /**
     * Sets intervalWidth
     *
     * @param int|null $intervalWidth The width of the histogram
     *
     * @return $this
     */
    public function setIntervalWidth($intervalWidth)
    {
        $this->container['intervalWidth'] = $intervalWidth;

        return $this;
    }

    /**
     * Gets intervals
     *
     * @return \Aylien\NewsApi\Models\HistogramInterval[]|null
     */
    public function getIntervals()
    {
        return $this->container['intervals'];
    }

    /**
     * Sets intervals
     *
     * @param \Aylien\NewsApi\Models\HistogramInterval[]|null $intervals The intervals of the histograms
     *
     * @return $this
     */
    public function setIntervals($intervals)
    {
        $this->container['intervals'] = $intervals;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


