<?php
/**
 * RelatedStories
 *
 * PHP version 5
 *
 * @category Class
 * @package  Aylien\NewsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aylien\NewsApi\Models;

use \ArrayAccess;
use \Aylien\NewsApi\ObjectSerializer;

/**
 * RelatedStories Class Doc Comment
 *
 * @category Class
 * @package  Aylien\NewsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RelatedStories implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RelatedStories';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'related_stories' => '\Aylien\NewsApi\Models\Story[]',
        'story_body' => 'string',
        'story_language' => 'string',
        'story_title' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'related_stories' => null,
        'story_body' => null,
        'story_language' => null,
        'story_title' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'related_stories' => 'related_stories',
        'story_body' => 'story_body',
        'story_language' => 'story_language',
        'story_title' => 'story_title'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'related_stories' => 'setRelatedStories',
        'story_body' => 'setStoryBody',
        'story_language' => 'setStoryLanguage',
        'story_title' => 'setStoryTitle'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'related_stories' => 'getRelatedStories',
        'story_body' => 'getStoryBody',
        'story_language' => 'getStoryLanguage',
        'story_title' => 'getStoryTitle'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['related_stories'] = isset($data['related_stories']) ? $data['related_stories'] : null;
        $this->container['story_body'] = isset($data['story_body']) ? $data['story_body'] : null;
        $this->container['story_language'] = isset($data['story_language']) ? $data['story_language'] : null;
        $this->container['story_title'] = isset($data['story_title']) ? $data['story_title'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets related_stories
     *
     * @return \Aylien\NewsApi\Models\Story[]|null
     */
    public function getRelatedStories()
    {
        return $this->container['related_stories'];
    }

    /**
     * Sets related_stories
     *
     * @param \Aylien\NewsApi\Models\Story[]|null $related_stories An array of related stories for the input story
     *
     * @return $this
     */
    public function setRelatedStories($related_stories)
    {
        $this->container['related_stories'] = $related_stories;

        return $this;
    }

    /**
     * Gets story_body
     *
     * @return string|null
     */
    public function getStoryBody()
    {
        return $this->container['story_body'];
    }

    /**
     * Sets story_body
     *
     * @param string|null $story_body The input story body
     *
     * @return $this
     */
    public function setStoryBody($story_body)
    {
        $this->container['story_body'] = $story_body;

        return $this;
    }

    /**
     * Gets story_language
     *
     * @return string|null
     */
    public function getStoryLanguage()
    {
        return $this->container['story_language'];
    }

    /**
     * Sets story_language
     *
     * @param string|null $story_language The input story language
     *
     * @return $this
     */
    public function setStoryLanguage($story_language)
    {
        $this->container['story_language'] = $story_language;

        return $this;
    }

    /**
     * Gets story_title
     *
     * @return string|null
     */
    public function getStoryTitle()
    {
        return $this->container['story_title'];
    }

    /**
     * Sets story_title
     *
     * @param string|null $story_title The input story title
     *
     * @return $this
     */
    public function setStoryTitle($story_title)
    {
        $this->container['story_title'] = $story_title;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


