<?php
/**
 * SentimentPolarity
 *
 * PHP version 5
 *
 * @category Class
 * @package  Aylien\NewsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aylien\NewsApi\Models;
use \Aylien\NewsApi\ObjectSerializer;

/**
 * SentimentPolarity Class Doc Comment
 *
 * @category Class
 * @description Polarity of the sentiment
 * @package  Aylien\NewsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SentimentPolarity
{
    /**
     * Possible values of this enum
     */
    const POSITIVE = 'positive';
    const NEUTRAL = 'neutral';
    const NEGATIVE = 'negative';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::POSITIVE,
            self::NEUTRAL,
            self::NEGATIVE,
        ];
    }
}


