<?php
/**
 * StoryLinksTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Aylien\NewsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@aylien.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aylien\NewsApi;

use PHPUnit\Framework\TestCase;

/**
 * StoryLinksTest Class Doc Comment
 *
 * @category    Class
 * @description StoryLinks
 * @package     Aylien\NewsApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class StoryLinksTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StoryLinks"
     */
    public function testStoryLinks()
    {
    }

    /**
     * Test attribute "canonical"
     */
    public function testPropertyCanonical()
    {
    }

    /**
     * Test attribute "coverages"
     */
    public function testPropertyCoverages()
    {
    }

    /**
     * Test attribute "permalink"
     */
    public function testPropertyPermalink()
    {
    }

    /**
     * Test attribute "relatedStories"
     */
    public function testPropertyRelatedStories()
    {
    }
}
