<?php
/**
 * StoryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Aylien\NewsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@aylien.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aylien\NewsApi;

use PHPUnit\Framework\TestCase;

/**
 * StoryTest Class Doc Comment
 *
 * @category    Class
 * @description Story
 * @package     Aylien\NewsApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class StoryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Story"
     */
    public function testStory()
    {
    }

    /**
     * Test attribute "author"
     */
    public function testPropertyAuthor()
    {
    }

    /**
     * Test attribute "body"
     */
    public function testPropertyBody()
    {
    }

    /**
     * Test attribute "categories"
     */
    public function testPropertyCategories()
    {
    }

    /**
     * Test attribute "charactersCount"
     */
    public function testPropertyCharactersCount()
    {
    }

    /**
     * Test attribute "clusters"
     */
    public function testPropertyClusters()
    {
    }

    /**
     * Test attribute "entities"
     */
    public function testPropertyEntities()
    {
    }

    /**
     * Test attribute "hashtags"
     */
    public function testPropertyHashtags()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "keywords"
     */
    public function testPropertyKeywords()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "media"
     */
    public function testPropertyMedia()
    {
    }

    /**
     * Test attribute "paragraphsCount"
     */
    public function testPropertyParagraphsCount()
    {
    }

    /**
     * Test attribute "publishedAt"
     */
    public function testPropertyPublishedAt()
    {
    }

    /**
     * Test attribute "sentencesCount"
     */
    public function testPropertySentencesCount()
    {
    }

    /**
     * Test attribute "sentiment"
     */
    public function testPropertySentiment()
    {
    }

    /**
     * Test attribute "socialSharesCount"
     */
    public function testPropertySocialSharesCount()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "summary"
     */
    public function testPropertySummary()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "translations"
     */
    public function testPropertyTranslations()
    {
    }

    /**
     * Test attribute "wordsCount"
     */
    public function testPropertyWordsCount()
    {
    }
}
