<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Aylien\NewsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AYLIEN News API
 *
 * The AYLIEN News API is the most powerful way of sourcing, searching and syndicating analyzed and enriched news content. It is accessed by sending HTTP requests to our server, which returns information to your client.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@aylien.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aylien\NewsApi;

use \Aylien\NewsApi\Configuration;
use \Aylien\NewsApi\ApiException;
use \Aylien\NewsApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aylien\NewsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for listAutocompletes
     *
     * List autocompletes.
     *
     */
    public function testListAutocompletes()
    {
    }

    /**
     * Test case for listClusters
     *
     * List Clusters.
     *
     */
    public function testListClusters()
    {
    }

    /**
     * Test case for listCoverages
     *
     * List coverages.
     *
     */
    public function testListCoverages()
    {
    }

    /**
     * Test case for listHistograms
     *
     * List histograms.
     *
     */
    public function testListHistograms()
    {
    }

    /**
     * Test case for listRelatedStories
     *
     * List related stories.
     *
     */
    public function testListRelatedStories()
    {
    }

    /**
     * Test case for listStories
     *
     * List Stories.
     *
     */
    public function testListStories()
    {
    }

    /**
     * Test case for listTimeSeries
     *
     * List time series.
     *
     */
    public function testListTimeSeries()
    {
    }

    /**
     * Test case for listTrends
     *
     * List trends.
     *
     */
    public function testListTrends()
    {
    }
}
